[pytest]
# onde o pytest deve procurar testes
testpaths = atividade/testes

# quais arquivos ele considera testes
python_files = test_*.py

# adiciona o diretório raiz (.) ao PYTHONPATH,
# assim 'src' vira um pacote importável
# sem precisar de sys.path nas fixtures
pythonpath = .
